# Site settings
title: Chen Cheng
email: ischen.cheng@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   I'm a senior undergraduate at the School of Information Science and Technology at ShanghaiTech University focusing on Human-AI Interaction (HAI).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.chencheng.me" # the base hostname & protocol for your site
production_url: "https://www.chencheng.me"
github_username:  ischencheng
permalink: /blog/:year/:month/:title.html

twitter:
  username: IsChenCheng

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
