# Site settings
title: Chen Cheng
email: ischen.cheng@gmail.edu
description: > # this means to ignore newlines until "baseurl:"
   Faculty at Carnegie Mellon University and Research Scientist at Apple. I create interactive data visualization and analysis tools. PhD from University of Washington.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.chencheng.de" # the base hostname & protocol for your site
production_url: "https://www.chencheng.de"
github_username:  ischencheng
permalink: /blog/:year/:month/:title.html

twitter:
  username: IsChenCheng

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
